markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: rjliulei.xyz
title: Rjliulei's Blog
description: Android, IOS, Java Web, PHP, reading...
author: Rjliulei
email: 772874830#qq.com
github: rjliulei

config:
  js_dir:
  img_dir:
  css_dir:
